// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn63bc5iWRSgG9sc40wivvkdksQplF5L4',
    appId: '1:656500100128:web:831f1ab6afb917d1d70045',
    messagingSenderId: '656500100128',
    projectId: 'ecommerce-app-a6d06',
    authDomain: 'ecommerce-app-a6d06.firebaseapp.com',
    storageBucket: 'ecommerce-app-a6d06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR0cWc8sPIJtbMpSgITssXMuiLZ8ZFGwM',
    appId: '1:656500100128:android:480f89ce3a889f19d70045',
    messagingSenderId: '656500100128',
    projectId: 'ecommerce-app-a6d06',
    storageBucket: 'ecommerce-app-a6d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzIHfxpCVJ4Khz18CdCsl8Fqz6Cu7kRg',
    appId: '1:656500100128:ios:3565a2f6335594c5d70045',
    messagingSenderId: '656500100128',
    projectId: 'ecommerce-app-a6d06',
    storageBucket: 'ecommerce-app-a6d06.appspot.com',
    androidClientId: '656500100128-1c0e5p52oq0smevc05r5f41kfs4ffa26.apps.googleusercontent.com',
    iosClientId: '656500100128-hoqv96uetleralm8bflf5qfp45620fed.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );
}
